version: '3.8'
services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bdd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  springboot:
    image: openjdk:21
    container_name: springboot
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]

volumes:
  postgres_data:
  mongo_data:
