services:
  postgresql:
    image: postgres:latest
    container_name: test
    volumes:
      - webServiceAtelierPostgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    container_name: mongodb-webServiceAtelier
    volumes:
      - webServiceAtelierMongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: webServiceAtelier_mongo
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  webServiceAtelierPostgres:
  webServiceAtelierMongo:
