services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-ProjetCatalogue
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
          - ProjetCataloguePostgres:/var/lib/postgresql/data
          - ./sql:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    container_name: mongodb-ProjetCatalogue
    volumes:
      - ProjetCatalogueMongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ProjetCatalogue_mongo
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  ProjetCataloguePostgres:
  ProjetCatalogueMongo:
